# Generated by Django 3.1.3 on 2020-11-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_2228'),
        ('code_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_editor.language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile'),
        ),
    ]
