# Generated by Django 3.1.3 on 2020-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0002_auto_20201124_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_version',
            field=models.CharField(default='Version', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='main_file_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
