# Generated by Django 3.1.3 on 2020-11-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_path',
            field=models.CharField(default='', max_length=150),
        ),
    ]
