# Generated by Django 3.1.3 on 2020-11-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201124_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_path',
            new_name='user_dir',
        ),
    ]
